name = "ParameterizedFunctions"
uuid = "65888b18-ceab-5e60-b2b9-181511a3b968"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "5.16.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
DataStructures = "0.17, 0.18"
DiffEqBase = "6.5"
DocStringExtensions = "0.8, 0.9"
Latexify = "0.14, 0.15, 0.16"
ModelingToolkit = "7, 8"
Reexport = "0.2, 1.0"
SciMLBase = "1.3, 2"
julia = "1.6"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["InteractiveUtils", "SpecialFunctions", "Test"]
