name = "ParameterizedFunctions"
uuid = "65888b18-ceab-5e60-b2b9-181511a3b968"
version = "5.21.0"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitBase = "7771a370-6774-4173-bd38-47e70ca0b839"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
Aqua = "0.8"
DataStructures = "0.18.13, 0.19"
DiffEqBase = "6.144"
DocStringExtensions = "0.9"
ExplicitImports = "1.14.0"
InteractiveUtils = "1.10"
Latexify = "0.16"
LinearAlgebra = "1.10"
ModelingToolkit = "11"
ModelingToolkitBase = "1"
Reexport = "1"
SciMLBase = "2.15"
SpecialFunctions = "2"
Symbolics = "7"
SymbolicUtils = "4"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ExplicitImports", "InteractiveUtils", "SpecialFunctions", "Test"]
